import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import MathsGuideStandardForm from "./maths-guide-1-2-standard-form-calculations";

export default function AdminPreview() {
  const [jsonInput, setJsonInput] = useState("");
  const [parsedContent, setParsedContent] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  const handlePreview = () => {
    try {
      const parsed = JSON.parse(jsonInput);
      setParsedContent(parsed);
      setError(null);
    } catch (e) {
      setError("Invalid JSON format. Please check your input.");
      setParsedContent(null);
    }
  };

  if (parsedContent) {
    return (
      <div className="relative">
        <div className="fixed top-4 left-1/2 -translate-x-1/2 z-50">
          <Button 
            onClick={() => setParsedContent(null)}
            variant="destructive"
            className="shadow-xl"
          >
            Exit Preview
          </Button>
        </div>
        <MathsGuideStandardForm content={parsedContent} />
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-secondary/30 p-8 flex items-center justify-center">
      <Card className="w-full max-w-4xl p-6 space-y-6">
        <div>
          <h1 className="text-2xl font-bold mb-2">Lesson Preview Tool</h1>
          <p className="text-muted-foreground">
            Paste the JSON generated by the Replit Agent Skill below to preview the lesson.
          </p>
        </div>

        <div className="space-y-2">
          <Textarea
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            placeholder='Paste your JSON here (starting with { "subject": ... })'
            className="min-h-[400px] font-mono text-sm"
          />
          {error && <p className="text-destructive text-sm font-medium">{error}</p>}
        </div>

        <div className="flex justify-end gap-3">
          <Button 
            onClick={() => setJsonInput("")} 
            variant="outline"
            disabled={!jsonInput}
          >
            Clear
          </Button>
          <Button onClick={handlePreview} disabled={!jsonInput}>
            Preview Lesson
          </Button>
        </div>
      </Card>
    </div>
  );
}
